title: Mu.js
description: µ.js ( Mu.js ) is a small helper Libary for Javascript. It does not implement jQuery but shares similar features and fields of applience.
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
